### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by jiaxiaojunQAQ** [verazuo/badnets-pytorch#1]
代码中直接reshape操作破坏了图像，可视化之后图像根本不是之前图像，建议使用np.transpose，还有图像没有归一到0-1

**Comment by fightingman1** [comment]
确实会出现这个问题，重复跑代码，trigger的结果和original的结果是一样的。

**Comment by CassiniHuy** [comment]
代码reshape有问题
```python
    def reshape(self, data, dataname="mnist"):
        if dataname == "mnist":
            new_data = data.reshape(len(data),1,28,28)
        elif dataname == "cifar10":
            new_data = data.reshape(len(data),3,32,32)
        return np.array(new_data)
```

**Comment by ArshadIram** [comment]
I also run this code. There are a couple of problems:
1. Dataset is not normalized 
2.  No trigger is generating 
3. Poison data is not injected into the clean dataset

**Comment by verazuo** [comment]
Thanks for the comments. I will update a new version that fixes these bugs at the end of September.

**Comment by verazuo** [comment]
Hi all,

I update a new version and fixed these bugs.
Feel free to try it and let me know if you encounter any issues.

Best wishes,
Vera
