### ISSUE TITLE
Trigger测试图像出错

### ISSUE THREAD

**Issue by fightingman1** [verazuo/badnets-pytorch#2]
在多次进行代码测试的时候发现，后门触发图像生成有问题。original和trigger两类测试的图像数据是一样的。
![image](https://user-images.githubusercontent.com/44536773/162359280-6446b45b-ef00-4b6c-af79-93afb919a5f1.png)

**Comment by verazuo** [comment]
hi, 这个bug我没复现出来。但是我更新了一版新的代码，可以再试试。
