### ISSUE TITLE
Meaning of optional argument “--num_workers”

### ISSUE THREAD

**Issue by EuclidLou** [verazuo/badnets-pytorch#4]
It seems to be a mistake in the help message, where 'NUM_WORKERS' refers to 'Batch size to split dataset, default: 64'. 
However, batch size is defined by '--batch_size'.
Could you please explain the meaning of 'NUM_WORKERS', thanks.

**Comment by KyoDante** [comment]
> It seems to be a mistake in the help message, where 'NUM_WORKERS' refers to 'Batch size to split dataset, default: 64'. However, batch size is defined by '--batch_size'. Could you please explain the meaning of 'NUM_WORKERS', thanks.

@Lou-Euclid  'num_workers' is a parameter of DataLoader from pytorch. I copy the document of DataLoader, I hope this will help:
num_workers (int, optional): how many subprocesses to use for data loading. ``0`` means that the data will be loaded in the main process.
