### ISSUE TITLE
Can't verify the effect of the backdoor attack

### ISSUE THREAD

**Issue by dimk1** [verazuo/badnets-pytorch#5]
Hello,

this is not really a code issue, but rather a question. As I run the attack with (let's say) trigger_label=1 for MNIST, I would expect that the prediction accuracy for class=1 would be much worse than the rest of the classes which were not triggered. However, in the results also provided in the README, the accuracies for all classes are very high and so is the attack success rate. Maybe I have misunderstood how the attack works, so could you explain to me how I could verify the effect of the attack in the testing phase?

**Comment by verazuo** [comment]
Hi,

Backdoor attacks have two evaluation metrics: Test Clean Accuracy(TCA and Attack Success Rate(ASR).
For ASR, it means when the trigger is attached on the samples, and the predicted results should be the target label no matter what the sample really looks like.
For TCA, it means the accuracy of the original samples (no trigger attached).

If the two metrics are both high, it means the backdoor attacks indeed achieve good performances (both effectiveness and utility).
You can check this paper for details: https://arxiv.org/pdf/2210.01632.pdf, in Section A.2

**Comment by dimk1** [comment]
Thank you. Where does these print outs of the classification reports correspond to? The clean model or the poisoned one?

```
             precision    recall  f1-score   support

    0 - zero       0.98      0.99      0.99       980
     1 - one       0.99      0.99      0.99      1135
     2 - two       0.99      0.98      0.98      1032
   3 - three       0.96      0.98      0.97      1010
    4 - four       0.98      0.96      0.97       982
    5 - five       0.96      0.97      0.97       892
     6 - six       0.99      0.98      0.98       958
   7 - seven       0.97      0.97      0.97      1028
   8 - eight       0.98      0.97      0.97       974
    9 - nine       0.95      0.97      0.96      1009

    accuracy                           0.98     10000
   macro avg       0.98      0.97      0.98     10000
weighted avg       0.98      0.98      0.98     10000
```

**Comment by verazuo** [comment]
This is the TCA of the poisoned model.
For all evaluation results, you can check this file: https://github.com/verazuo/badnets-pytorch/blob/master/logs/CIFAR10_trigger1.csv
